version: '3.12'

services:
  db:
    restart: always
    image: postgres:12.0-alpine
    container_name: db
    volumes:
      - referral_library_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  web:
    build: .
    container_name: referral_system
    restart: always
    command: bash runserver_and_migration.sh
    volumes:
      - .:/Users/alexander/referral_system
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    env_file:
      - .env
    depends_on:
      - db

volumes:
  referral_library_postgres_data:
