# Generated by Django 5.0.2 on 2024-02-08 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referralcode",
            name="used_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="used_referral_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="referralcode",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_code_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
